# Generated by Django 4.0.4 on 2022-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='creacion',
            field=models.IntegerField(),
        ),
    ]
